branch-defaults:
  docker:
    environment: dev-env
    group_suffix: null
global:
  application_name: awsTest
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-west-2
  profile: eb-cli
  sc: git
